import pyautogui
import webbrowser
from time import sleep

webbrowser.open('https://web.whatsapp.com/')
sleep(10)
botao_pesquisa = pyautogui.locateCenterOnScreen('whatsapp_1.png')
pyautogui.click(botao_pesquisa)
sleep(2)
pyautogui.typewrite('Leonardo Orizio')
sleep(2)
pyautogui.moveTo(351,494, duration=0.5)
pyautogui.click()
sleep(2)
botao_escrita = pyautogui.locateCenterOnScreen('whatsapp_2.png')
pyautogui.click(botao_escrita)
sleep(2)
pyautogui.typewrite('Bom dia, Leonardo! Tudo bem?')
pyautogui.hotkey('enter')
sleep(2)
pyautogui.moveTo(250,282, duration=0.5)
pyautogui.click()
sleep(2)
pyautogui.typewrite('Amor')
sleep(2)
pyautogui.moveTo(351,494, duration=0.5)
pyautogui.click()
sleep(2)
botao_escrita = pyautogui.locateCenterOnScreen('whatsapp_2.png')
pyautogui.click(botao_escrita)
sleep(2)
pyautogui.typewrite('Bom dia, Nayara! Tudo bem?')
pyautogui.hotkey('enter')